[project]
name = "py-2025"
version = "0.1.0"
description = "How to setup a Python project the right way in 2025"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "ruff>=0.11.4",
]
